### ISSUE TITLE
Najnowsza wersja aplikacji nie działa 

### ISSUE THREAD

**Issue by yehorscode** [VulkaProject/Vulka-Android#1]
Hej!
Apka instaluje się lecz przy otwieraniu zamyka się od razu
Gduby potrzebne były jakieś informacje o systemie pisz ;)

**Comment by tomaszk8266** [comment]
To jest standardowy błąd, występuje przy jakimkolwiek upgrade, zapewne jest spowodowany brakiem kompatybilności wstecznej bazy danych, trzeba przeinstalować apkę, wtedy działa

**Comment by M3DZIK** [comment]
Jest to wersja "nightly" więc narazie jest to wczesna wersja aplikacji. Aktualnie do momentu wydanie pierwszej finalnej wersji nie będą dodawane migracje bazy danych (bo jest to bez sensu aktualnie), tak więc czasami będzie się tak teraz dziać. Wystarczy wyczyścić dane aplikacji i od nowa się zalogować.

Od momentu dodanie wszytskich funkcji i wydania pierwszej wersji finalnej / beta tego problemu już nie będzie.

**Comment by yehorscode** [comment]
Okej, problem zniknął jak odinstalowałem 2 razy i zainstalowałem tez dwa razy
