### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by tomaszk8266** [VulkaProject/Vulka-Android#10]
Mam dużo drobnych sugestii co do aplikacji, ale nie chce mi się otwierać dla każdej nowego issue... Do tego idealny byłby discord. Najlepiej żeby był zrobiony mniej więcej tak jak kiedyś ten Wulkanowego.

**Comment by rafi612** [comment]
Napewno będzie, ale aktualnie nie mam czasu zbytnio na konfigurację kanałów, jeszcze dzisiaj postaram się go zrobić na sucho i wysłać linka, może odczeka jakiś czas zanim go skonfiguruję.

**Comment by M3DZIK** [comment]
https://discord.com/invite/BbPFHYa7FR

Stworzyłem, ale jeszcze niedokońca jest skonfigurowany.
