### ISSUE TITLE
Segmented button w wyborze semestrów

### ISSUE THREAD

**Issue by tomaszk8266** [VulkaProject/Vulka-Android#7]
Wybór semestru oparty na zwykłych buttonach jest o niebo lepszy od tego, co było w Wulkanowym (dość nieintuicyjny przycisk zmiany semestrów w górnym pasku), ale ciągle wygląda tak sobie, ja bym użył [segmented buttonów](https://m3.material.io/components/segmented-buttons/overview). Trzeba by pokombinować z AndroidView, bo compose nie jest jak na razie wspierany, ale myślę, że nie byłoby to trudne.

**Comment by rafi612** [comment]
Przyciski do wyboru semestrów to narazie placeholder, najpierw chciałem dodać taki jak w wulkanowym ale też średnio mi się podobał, myślałem też nad czymś podobnym jak jest w Vulcanova. Segmented Buttony wydają się nawet fajne. Pokombinujemy z ich dodaniem.

**Comment by rafi612** [comment]
Dodane w https://github.com/VulkaProject/Vulka-Android/commit/12a823203fb1d3795f588c22e882ee17d3bb4143
