### ISSUE TITLE
Logowanie do Vulcana przy użyciu loginu i hasła

### ISSUE THREAD

**Issue by tomaszk8266** [VulkaProject/Vulka-Android#8]
Logowanie do vulcana za pomocą loginu i hasła, mniej więcej tak jak robi to szkolny.eu (tam po wpisaniu loginu i hasła apka loguje się i generuje sobie dane do rejestracji). Zrobiłbym to jednak nieco inaczej, to znaczy z headless webview mniej więcej tak jak Wulkanek (byłoby to bardziej odporne na zmiany).

**Comment by rafi612** [comment]
Jest taki plan, miało to działać na zasadzie zwykłego scrappera, jednak jest to dość ryzykowne i podatne na zmiany. Nie myślałem najpierw o webview jednak może być całkiem dobre rozwiązanie. Chociaż nie wiem co z eduone, nie mam go jak testować narazie, a z tego co słyszałem to do września eduone ma być już używane w wszystkich szkołach. Zobaczymy jak to będzie wyglądać we wrześniu.

**Comment by tomaszk8266** [comment]
Szkoda, bo teraz podczas ciągłych zmian w db trzeba często przeinstalowywać aplikację i się logować... Wulkanowy jeszcze działa i jest git jak na razie, ale jak przestanie to trzeba będzie się ciągle do przeglądarki logować, bo Wulkanek nie chce dodać wsparcia dla dostępu mobilnego...
